### ISSUE TITLE
Implementare i "frammenti"

### ISSUE THREAD

**Issue by giuseb** [giuseb/titolele#6]
Cattura automaticamente due o più parole che formano un concetto (termine) unico:
- Unione Europea
- tour de force
- su quì, quò e quà laccento non va

eccetera

**Comment by rosencra** [comment]
E come si fa? Lo hai già messo e non lo vedo?

**Comment by giuseb** [comment]
ancora da fare

**Comment by giuseb** [comment]
Ora c'è un abbozzo di funzionalità.
- http://titolele.herokuapp.com/titles/244
- come vedi compaiono i termini 'piazza' e 'affari'
- premi T (o fai click su Nuovo termine)
- nel campo 'Variante' scrivi la stringa da cercare, in questo caso "piazza affari" (nota il minuscolo)
- nel campo Radice puoi scrivere "Piazza Affari" o anche "Borsa di Milano" (dipende da quanto li percepisci come indistinguibili o se ha un senso mantenere termini distinti, da linkare in un secondo tempo).
- click su Salva
- di nuovo nella pagina del titolo, premi Scan
- vualà
